apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
    {{ include "devops-interview.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["api"]
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            {{ include "devops-interview.env" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
